import AsyncStorage from '@react-native-async-storage/async-storage';
import React, { createContext, ReactNode, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'th';

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => Promise<void>;
  t: (key: string, params?: Record<string, any>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const STORAGE_KEY = 'app_language';

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setCurrentLanguage] = useState<Language>('en');

  const loadLanguage = async () => {
    try {
      const savedLanguage = await AsyncStorage.getItem(STORAGE_KEY);
      if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'th')) {
        setCurrentLanguage(savedLanguage as Language);
      }
    } catch (error) {
      console.error('Error loading language:', error);
    }
  };

  const setLanguage = async (newLanguage: Language) => {
    try {
      await AsyncStorage.setItem(STORAGE_KEY, newLanguage);
      setCurrentLanguage(newLanguage);
    } catch (error) {
      console.error('Error saving language:', error);
    }
  };

  const t = (key: string, params?: Record<string, any>): string => {
    let translation = translations[language]?.[key] || translations.en[key] || key;

    if (params) {
      Object.keys(params).forEach(paramKey => {
        translation = translation.replace(new RegExp(`{{${paramKey}}}`, 'g'), params[paramKey]);
      });
    }

    return translation;
  };

  useEffect(() => {
    loadLanguage();
  }, []);

  const value: LanguageContextType = {
    language,
    setLanguage,
    t,
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Translation data
const translations: Record<Language, Record<string, string>> = {
  en: {
    // Navigation & Common
    'back': 'Back',
    'next': 'Next',
    'confirm': 'Confirm',
    'cancel': 'Cancel',
    'all': 'All',
    'save': 'Save',
    'edit': 'Edit',
    'delete': 'Delete',
    'search': 'Search',
    'loading': 'Loading...',
    'error': 'Error',
    'success': 'Success',

    // Tabs
    'home': 'Home',
    'pets': 'Pets',
    'pet': 'Pet',
    'services': 'Services',
    'privileges': 'Privileges',
    'profile': 'Profile',

    // Content & Articles
    'articles': 'Articles',
    'news': 'News',
    'coupons': 'Coupons',
    'bookings': 'Bookings',
    'expires': 'Expires',
    'allArticles': 'All Articles',
    'newsAndAnnouncements': 'News & Announcements',
    'allCoupons': 'All Coupons',
    'myServices': 'My Services',
    'myBookings': 'My Bookings',
    'content': 'Content',
    'noArticlesFound': 'No articles found in this category',
    'noNewsFound': 'No news or announcements found',
    'noCouponsFound': 'No coupons found',
    'noServicesFound': 'No services found',
    'noBookingsFound': 'No bookings found',
    'noBookings': 'No Bookings',
    'noBookingsDescription': 'You have no bookings yet. Book a service to see them here.',
    'noContentFound': 'No content found',
    'loadingArticles': 'Loading articles...',
    'announcement': 'Announcement',
    'readyToUse': 'Ready to Use',
    'unknown': 'Unknown',
    'upcoming': 'Upcoming',
    'completed': 'Completed',

    // Hotel Booking
    'bookRoom': 'Book Room',
    'bookingDetails': 'Booking Details',
    'selectDates': 'Select Dates',
    'checkIn': 'Check-in',
    'checkOut': 'Check-out',
    'nightsPlural': 'nights',
    'night': 'night',
    'selectPets': 'Select Pets',
    'selectPetsDescription': 'Choose which pets you want to book for (max {{max}})',
    'noPetsAvailable': 'No pets available for this hotel type',
    'addPetFirst': 'Add a new pet first',
    'bookingSummary': 'Booking Summary',
    'totalCost': 'Total Cost',
    'confirmBooking': 'Confirm Booking',
    'bookingConfirmed': 'Booking Confirmed!',
    'roomBooked': 'Your room has been successfully booked.',
    'roomSize': 'Room Size',
    'roomCapacity': 'Room Capacity',
    'bookingId': 'Booking ID',
    'bookingDate': 'Booking Date',
    'totalNights': 'Total Nights',
    'bookingError': 'Booking Error',
    'selectRoom': 'Select Room',
    'selectRoomDescription': 'Select a room for your pet',
    'noRoomsAvailable': 'No rooms available for the selected date. Please choose another date or room.',

    // Pet Details
    'petName': 'Pet Name',
    'breed': 'Breed',
    'age': 'Age',
    'weight': 'Weight',
    'years': 'years',
    'kg': 'kg',

    // Services
    'serviceDetail': 'Service Detail',
    'keyFeatures': 'Key Features',
    'whatsIncluded': "What's Included",
    'bookService': 'Book {{service}}',

    // Rewards
    'rewardDetail': 'Reward Detail',
    'pointsRequired': '{{points}} points',
    'redeemFor': 'Redeem for {{points}} points',
    'termsConditions': 'Terms & Conditions',
    'currentlyUnavailable': 'Currently Unavailable',
    'temporarilyUnavailable': 'This reward is temporarily unavailable. Please check back later.',

    // Room Details
    'roomDetails': 'Room Details',
    'perNight': 'per night',
    'size': 'Size',
    'capacity': 'Capacity',
    'petSingular': 'pet',
    'petPlural': 'pets',
    'roomAmenities': 'Room Amenities',
    'bookingConditions': 'Booking Conditions',
    'bookThisRoom': 'Book This Room',
    'roomUnavailable': 'Room Unavailable',
    'selectDatesNote': 'You can select dates and pets in the next step',

    // Settings/Profile
    'language': 'Language',
    'english': 'English',
    'thai': 'ไทย',
    'changeLanguage': 'Change Language',

    // Categories
    'food': 'Food',
    'toys': 'Toys',
    'accessories': 'Accessories',
    'medicine': 'Medicine',
    'grooming': 'Grooming',
    'training': 'Training',
    'boarding': 'Boarding',
    'spa': 'Spa',
    'medical': 'Medical',
    'health': 'Health',
    'nutrition': 'Nutrition',
    'veterinary': 'Veterinary',
    'emergency': 'Emergency',
    'preventive': 'Preventive',
    'specialist': 'Specialist',
    'general': 'General Care',

    // Status
    'available': 'Available',
    'unavailable': 'Unavailable',
    'inStock': 'In Stock',
    'outOfStock': 'Out of Stock',
    'add': 'Add',

    // Home Screen
    'welcomeToPetShop': 'Welcome to PetShop',
    'petArticles': 'Pet Articles',
    'currentBookings': 'Current Bookings',

    // Pet Card & Form
    'medicalInformation': 'Medical Information',
    'healthInformation': 'Health Information',
    'attendingVeterinarian': 'Attending Veterinarian',
    'lastSeen': 'Last Seen',
    'nextAppointment': 'Next Appointment',
    'congenitalDiseases': 'Congenital Diseases',
    'allergies': 'Allergies',
    'none': 'None',
    'yearsOld': 'years',
    'weightKg': '{{weight}}kg',
    'na': 'N/A',
    'at': 'at',

    // Booking Form
    'book': 'Book',
    'selectPetsLabel': 'Select Pets',
    'date': 'Date',
    'time': 'Time',
    'specialNotes': 'Special Notes',
    'anySpecialRequirements': 'Any special requirements...',
    'bookingAndSummary': 'Booking Summary',
    'serviceLabel': 'Service: {{service}}',
    'petsSelected': 'Pets: {{count}} selected',
    'total': 'Total: ฿{{amount}}',
    'bookNow': 'Book Now',
    'errorSelectPets': 'Please select at least one pet',
    'errorSelectDateTime': 'Please select date and time',
    'datePlaceholder': 'YYYY-MM-DD',
    'timePlaceholder': 'HH:MM',

    // Alert Messages
    'lazadaAppNotFound': 'Lazada App Not Found',
    'wouldYouLikeToDownload': 'Would you like to download the Lazada app or visit the website?',
    'downloadApp': 'Download App',
    'openWebsite': 'Open Website',
    'unableToOpenLazada': 'Unable to open Lazada. Please try again later.',

    // Common UI Elements
    'viewAll': 'View All',
    'seeMore': 'See More',
    'readMore': 'Read More',

    // Profile Menu
    'menu': 'Menu',
    'myBookingsSubtitle': 'View your service history',
    'myCouponsSubtitle': 'View your usable and used coupons',
    'notifications': 'Notifications',
    'notificationsSubtitle': 'Manage your alerts',
    'settings': 'Settings',
    'settingsSubtitle': 'App preferences',
    'helpSupport': 'Help & Support',
    'helpSupportSubtitle': 'Get assistance',
    'aboutPetShop': 'About PetShop',
    'aboutPetShopSubtitle': 'App information',
    'signOut': 'Sign Out',

    // Services Screen
    'petServices': 'Pet Services',
    'allServices': 'All Services',
    'petBoarding': 'Pet Boarding',
    'petBoardingDesc': 'Safe and comfortable boarding for your pets while you\'re away',
    'professionalGrooming': 'Professional Grooming',
    'professionalGroomingDesc': 'Complete grooming service including bath, nail trim, and styling',
    'dogTraining': 'Dog Training',
    'dogTrainingDesc': 'Professional training sessions for basic obedience and behavior',
    'petSpa': 'Pet Spa',
    'petSpaDesc': 'Relaxing spa treatment for your beloved pets',
    'veterinaryCheckup': 'Veterinary Checkup',
    'veterinaryCheckupDesc': 'Comprehensive health examination by experienced veterinarians',

    // My Pets Screen
    'myPets': 'My Pets',
    'addNewPet': 'Add New Pet',
    'noPetsYet': 'No pets added yet',
    'addFirstPet': 'Add your first pet to get started',
    'removePet': 'Remove Pet',
    'removePetConfirm': 'Are you sure you want to remove {{name}} from your pets?',
    'remove': 'Remove',

    // Add Pet Screen
    'addPetTitle': 'Add New Pet',
    'petPhoto': 'Pet Photo',
    'selectPhoto': 'Select Photo',
    'petType': 'Pet Type',
    'dog': 'Dog',
    'cat': 'Cat',
    'other': 'Other',
    'petDetails': 'Pet Details',
    'enterPetName': 'Enter pet name',
    'enterBreed': 'Enter breed',
    'enterAge': 'Enter age in years',
    'enterWeight': 'Enter weight in kg',
    'medicalInfo': 'Medical Information',
    'allergiesOptional': 'Allergies (optional)',
    'enterAllergies': 'Enter known allergies',
    'congenitalDiseasesOptional': 'Congenital Diseases (optional)',
    'enterDiseases': 'Enter any congenital diseases',
    'veterinarianInfo': 'Veterinarian Information',
    'vetName': 'Veterinarian Name',
    'enterVetName': 'Enter veterinarian name',
    'vetPhone': 'Phone Number',
    'enterVetPhone': 'Enter phone number',
    'addPet': 'Add Pet',
    'fillRequiredFields': 'Please fill in all required fields',
    'petNameRequired': 'Pet name is required',
    'breedRequired': 'Breed is required',
    'ageRequired': 'Age is required',
    'validAge': 'Please enter a valid age',
    'weightRequired': 'Weight is required',
    'validWeight': 'Please enter a valid weight',
    'validPhone': 'Please enter a valid phone number',
    'petAddedSuccess': '{{name}} has been added to your pets!',
    'basicInformation': 'Basic Information',
    'healthInformationForm': 'Health Information',
    'multipleItemsComma': 'Enter multiple items separated by commas',
    'veterinaryInformation': 'Veterinary Information',
    'optionalAddLater': 'Optional - You can add this later',
    'enterPetNamePlaceholder': 'Enter your pet\'s name',
    'breedExample': 'e.g., Golden Retriever, Persian',
    'ageYears': 'Age (years)',
    'petInformation': 'Pet Information',
    'fillAllRequiredFields': 'Please fill all required fields',
    'registerNewFamily': 'Register your new family member',
    'physicalDetails': 'Physical Details',
    'separateWithCommas': 'Separate with commas',
    'attendingVeterinarianName': 'Attending Veterinarian Name',
    'attendingVeterinarianPhone': 'Attending Veterinarian Phone',
    'ageInYears': 'Age in years',
    'weightInKg': 'Weight in kg',
    'enterCongenitalDiseases': 'Enter congenital diseases',
    'petAddedSuccessfully': 'Pet added successfully',
    'failedToAddPet': 'Failed to add pet',
    'pleaseCompleteRequiredFields': 'Please complete all required fields',
    'validationError': 'Validation Error',
    'bathGrooming': 'Bath & Grooming',
    'bookGrooming': 'Book Grooming',
    'selectedService': 'Selected Service',
    'selectDate': 'Select Date',
    'selectTime': 'Select Time',
    'selectPetsForGrooming': 'Choose which pets you want to book for grooming',
    'selectedDate': 'Selected Date',
    'totalPrice': 'Total Price',
    'booking': 'Booking...',
    'groomingBookingSuccess': 'Your {{service}} appointment has been successfully booked!',
    'serviceUnavailable': 'Service Unavailable',
    'serviceCurrentlyUnavailable': 'This service is currently not available. Please try again later.',
    'noServicesInThisCategory': 'No services found in this category',
    'weightKgLabel': 'Weight (kg)',
    'allergiesExample': 'e.g., chicken, dairy, peanuts (optional)',
    'diseasesExample': 'e.g., hip dysplasia, heart murmur (optional)',
    'attendingVet': 'Attending Veterinarian',
    'drExample': 'Dr. John Smith (optional)',
    'veterinarianPhone': 'Veterinarian Phone',
    'phoneExample': '+66-2-555-0123 (optional)',

    // Privileges Screen
    'privilegesRewards': 'Privileges & Rewards',
    'pointsBalance': 'Points Balance',
    'points': 'Points',
    'availableRewards': 'Available Rewards',
    'redeem': 'Redeem',
    'redeemPoints': 'Redeem {{points}} Points',
    'insufficientPoints': 'Insufficient Points',

    // Coupons Screen
    'myCoupons': 'My Coupons',
    'myCouponsTitle': 'My Coupons',
    'availableCoupons': 'Available Coupons',
    'usedCoupons': 'Used Coupons',
    'expiredCoupons': 'Expired Coupons',
    'validUntil': 'Valid until',
    'useCoupon': 'Use Coupon',
    'expired': 'Expired',
    'used': 'Used',
    'service': 'Service',
    'product': 'Product',
    'special': 'Special',
    'couponNotFound': 'Coupon not found',
    'expiresOn': 'Expires',
    'redeemed': 'Redeemed:',
    'pointsLabel': '{{points}} points',
    'availableCount': 'Available ({{count}})',
    'usedExpiredCount': 'Used & Expired ({{count}})',
    'noAvailableCoupons': 'No Available Coupons',
    'noUsedExpiredCoupons': 'No Used or Expired Coupons',
    'redeemRewardsMessage': 'Redeem rewards from the privileges section to get coupons you can use',
    'usedExpiredMessage': 'Your used and expired coupons will appear here',

    // Coupon Types
    'freeBasicGrooming': 'Free Basic Grooming',
    'freeBasicGroomingDesc': 'Complete grooming service for small pets including bath, nail trimming, and basic styling. Perfect for keeping your pet clean and healthy.',
    'premiumToyBundle': 'Premium Toy Bundle',
    'premiumToyBundleDesc': 'Collection of premium toys for your pet including interactive puzzle toys, rope toys, and squeaky toys.',
    'discountPremiumFood': '20% Off Premium Food',
    'discountPremiumFoodDesc': 'Discount on premium pet food brands',
    'petTrainingSession': 'Pet Training Session',
    'petTrainingSessionDesc': 'One-on-one training session with professional trainer',
    'vipSpaPackage': 'VIP Spa Package',
    'vipSpaPackageDesc': 'Luxury spa treatment with massage and aromatherapy',

    // Booking History
    'bookingHistory': 'Booking History',
    'upcomingBookings': 'Upcoming',
    'pastBookings': 'Past',
    'cancelledBookings': 'Cancelled',
    'bookingOn': 'Booking on',
    'status': 'Status',
    'confirmed': 'Confirmed',
    'pending': 'Pending',
    'cancelled': 'Cancelled',

    // Service Detail
    'bookThisService': 'Book This Service',
    'pricePerSession': '฿{{price}} per session',
    'serviceIncludes': 'Service Includes',
    'bookingInformation': 'Booking Information',
    'keyFeaturesService': 'Key Features',
    'whatsIncludedService': 'What\'s Included',
    'serviceNotFound': 'Service not found',
    'myServiceDetail': 'My Service Detail',
    'serviceUsed': 'Used',
    'serviceExpired': 'Expired',
    'purchased': 'Purchased on',
    'purchasedOn': 'Purchased on',
    'expiresOnDate': 'Expires on',
    'usedOn': 'Used on',
    'useService': 'Use Service',
    'confirmUseService': 'Are you sure you want to use this service?',
    'serviceUsedMessage': 'Service has been marked as used successfully.',
    'loadingServices': 'Loading services...',
    'noServices': 'No services found',
    'noServicesDescription': 'Your purchased services will appear here.',
    'viewDetails': 'View Details',
    'premiumService': 'Premium Service',
    'bookAgain': 'Book Again',
    'purchaseAgain': 'Purchase Again',
    'purchaseService': 'Purchase Service',
    'purchaseServiceConfirmation': 'Are you sure you want to purchase {{name}} for {{price}}?',
    'purchase': 'Purchase',
    'unknownService': 'Unknown Service',
    'purchaseSuccess': 'Purchase Successful',
    'viewMyServices': 'View My Services',
    'servicePurchasedSuccessfully': '{{name}} has been purchased successfully!',
    'bookingSuccess': 'Booking Successful',
    'serviceBookedSuccessfully': 'Service has been booked successfully!',

    // Service Types & Descriptions
    'climatControlled': 'Climate-controlled private rooms',
    'regularFeeding': 'Regular feeding schedule',
    'dailyExercise': 'Daily exercise and playtime',
    'petSocialization': 'Socialization with other pets',
    'staffSupervision': '24/7 staff supervision',
    'emergencyVetCare': 'Emergency veterinary care',
    'dailyPhotoUpdates': 'Daily photo updates',
    'optionalGrooming': 'Grooming service (optional)',
    'bathAndDry': 'Professional bath and dry',
    'nailTrimming': 'Nail trimming and filing',
    'earCleaning': 'Ear cleaning and inspection',
    'furStyling': 'Professional fur styling',
    'premiumProducts': 'Premium shampoo and conditioner',
    'healthCheckDuring': 'Basic health check during service',

    // Pet Hospital
    'petHospital': 'Pet Hospital',
    'petHospitalDescription': "Connect with expert vets for complete care, ensuring your pet's health and happiness.",
    'chooseHospitalType': 'Choose Hospital Type',
    'selectHospitalForPet': 'Select the type of medical care your pet needs',
    'specialistHospital': 'Specialist Veterinarian',
    'specialistHospitalDesc': 'Expert care for complex conditions and specialized treatments',
    'generalHospital': 'General Veterinarian',
    'generalHospitalDesc': 'Routine check-ups, vaccinations, and general health care',
    'bookAppointment': 'Book Appointment',
    'availableSlots': 'Available Time Slots',
    'fullyBooked': 'Fully Booked',
    'additionalInformation': 'Additional Information',
    'describeSymptoms': 'Please describe your pet\'s symptoms or concerns',
    'confirmAppointment': 'Confirm Appointment',

    // Pet Hotel
    'petHotel': 'Pet Hotel',
    'roomTypes': 'Room Types',
    'standardRoom': 'Standard Room',
    'deluxeRoom': 'Deluxe Room',
    'suiteRoom': 'Suite Room',
    'viewRooms': 'View Available Rooms',
    'bookHotel': 'Book Hotel Stay',
    'nights': '{{count}} nights',
    'totalAmount': 'Total Amount',
    'petCapacity': 'Pet Capacity',
    'roomType': 'Room Type',
    'amenities': 'Amenities',
    'specialRequestsPlaceholder': 'e.g., special food requirements, medication, daily routine...',

    // Quick Actions
    'quickBooking': 'Quick Booking',
    'emergencyVet': 'Emergency Vet',
    'petGrooming': 'Pet Grooming',
    'petStore': 'Pet Store',

    // New Translation Keys
    'groomingService': 'Grooming Service',
    'cannotBeCancelled': 'Cannot be cancelled',
    'noUpcomingBookings': 'You have no upcoming bookings',
    'noCompletedBookings': 'You have no completed bookings',
    'noBookingsYet': 'You haven\'t made any bookings yet',
    'choosePetType': 'Choose Your Pet Type',
    'selectHotelForPet': 'Select the hotel designed specifically for your pet',
    'dogHotel': 'Dog Hotel',
    'catHotel': 'Cat Hotel',
    'hotelNotFound': 'Hotel not found',
    'hotelRooms': 'Hotel Rooms',
    'loadingRooms': 'Loading rooms...',
    'availableRooms': 'Available Rooms',
    'allRooms': 'All Rooms',
    'superiorRoom': 'Superior',
    'suite': 'Suite',
    'more': 'more',
    'selectDatesNextStep': 'You can select dates and pets in the next step',
    'checkInDate': 'Check-in Date',
    'checkOutDate': 'Check-out Date',
    'selectPetsMax': 'Select Pets (Max {{max}})',
    'selectedOfMax': 'Selected: {{selected}} of {{max}}',
    'selectAtLeastOnePet': 'Please select at least one pet for this booking.',
    'bookingDetailsConfirm': 'Booking Details:\\n\\n• Hotel: {{hotel}}\\n• Room: {{room}}\\n• {{pets}}: {{petNames}}\\n• Check-in: {{checkIn}}\\n• Check-out: {{checkOut}}\\n• Nights: {{nights}}\\n• Total: ${{total}}\\n\\nConfirm this booking?',
    'bookingConfirmationMessage': 'Your hotel booking has been confirmed!\\n\\nBooking ID: {{bookingId}}\\n\\nYou will receive a confirmation email shortly.',
    'bookingInfoNotFound': 'Booking information not found',
    'professionalVeterinaryCare': 'Professional Veterinary Care',
    'chooseSpecialistVeterinarians': 'Choose from our specialist veterinarians to provide the best care for your beloved pet',
    'selectSpecialist': 'Select a Specialist',
    'selectBookAppointment': 'Select & Book Appointment',
    'specialistNotFound': 'Specialist not found',
    'booked': 'Booked',
    'additionalInfoOptional': 'Additional Information (Optional)',
    'appointmentReason': 'Appointment Reason',
    'appointmentReasonPlaceholder': 'e.g., Regular checkup, vaccination, follow-up visit...',
    'initialSymptoms': 'Initial Symptoms',
    'symptomsPlaceholder': 'Describe any symptoms you\'ve noticed...',
    'requestSpecificVet': 'Request Specific Veterinarian',
    'vetNamePlaceholder': 'Enter veterinarian name if you have a preference...',
    'additionalNotes': 'Additional Notes',
    'additionalNotesPlaceholder': 'Any additional information for the veterinarian...',
    'bookingsCannotBeCancelled': 'Bookings cannot be cancelled once confirmed',
    'incompleteInformation': 'Incomplete Information',
    'selectTimeAndPet': 'Please select a time and pet for the appointment.',
    'bookingCannotBeCancelledConfirm': 'IMPORTANT: This booking cannot be cancelled once confirmed.\nAre you sure you want to proceed?',
    'appointmentBookedSuccessfully': 'Your appointment has been booked successfully.\\n\\nBooking ID: {{bookingId}}\\n\\nYou will receive a confirmation email shortly.',
    'bookingInProgress': 'Booking...',
    'loadingBookings': 'Loading bookings...',
    'loadingBookingData': 'Loading booking data...',
    'failedToCreateBooking': 'Failed to create booking',
    'bookingFailed': 'Booking Failed',

    // Bath & Grooming (Additional keys)
    'professionalGroomingServices': 'Professional Grooming Services',
    'chooseGroomingService': 'Choose from our professional grooming services to keep your pet clean and healthy',
    'selectGroomingService': 'Select a Grooming Service',
    'included': 'Included',
    'selectService': 'Select Service',
    'changeService': 'Change Service',
    'selectPet': 'Select Pet',
    'choosePetForGrooming': 'Choose which pet you would like to book grooming service for',
    'yearsOldSimple': 'years old',
    'bookGroomingService': 'Book Grooming Service',
    'groomingBookingNote': 'Your grooming appointment will be confirmed shortly',
    'selectServiceAndPet': 'Please select a grooming service and pet for the booking.',
    'groomingBookingConfirmedTitle': 'Booking Confirmed',
    'groomingBookingConfirmedMessage': 'Your grooming service has been booked successfully!\\n\\nService: {{service}}\\nPet: {{pet}}\\nPrice: ${{price}}\\nDuration: {{duration}}\\nBooking ID: {{bookingId}}\\n\\nWe will contact you to schedule the appointment.',
    'ok': 'OK',
    'bath': 'Bath',
    'combo': 'Combo',
    'comboPackages': 'Combo Packages',

    // Loyalty Card
    'PetShopPoints': 'PetShop Points',
    'loyaltyRewards': 'Loyalty Rewards',
    'member': 'MEMBER',
    'availablePoints': 'Available Points',
    'earnedTotal': '{{points}} earned total',

    // Services
    'noServicesAvailable': 'No services available',

    // Coupon Detail
    'couponDetail': 'Coupon Detail',
    'loadingCouponDetail': 'Loading coupon details...',
    'retry': 'Retry',
    'discount': 'Discount',
    'percentageDiscount': 'Percentage Discount',
    'fixedDiscount': 'Fixed Amount Discount',
    'termsAndConditions': 'Terms & Conditions',
    'useCouponConfirm': 'Are you sure you want to use this coupon?',
    'useCouponSuccess': 'Coupon used successfully!',
    'confirmUseCoupon': 'Confirm Use Coupon',
    'couponUsed': 'Coupon Used',
    'couponUsedDescription': 'This coupon has already been used and cannot be used again.',
    'couponExpired': 'Coupon Expired',
    'couponExpiredDescription': 'This coupon has expired and is no longer valid.',
    'noImage': 'No Image Available',
    'usingCoupon': 'Using Coupon...',

    // Service Detail - Missing Keys
    'petBoardingFull': 'Comprehensive pet boarding service with 24-hour supervision, comfortable accommodations, regular meals, and daily exercise. Your pets will be cared for in a safe, clean environment with experienced staff.',
    '24hourSupervision': '24-hour staff supervision',
    'comfortableAccommodation': 'Comfortable accommodation',
    'feedingService': 'Regular feeding service',
    'playTime': 'Daily play time',
    'emergencyVetAccess': 'Emergency veterinary access',
    'vaccinationRecord': 'Current vaccination records required',
    'advanceBooking': 'Advance booking recommended',
    'petHealthCertificate': 'Pet health certificate required',
    'pickupDropoffAvailable': 'Pickup and drop-off service available',
    'specialDietAccommodated': 'Special dietary needs accommodated',
    'medicationAdministered': 'Medication administration available',
    'professionalGroomingFull': 'Complete professional grooming service including bath, nail trimming, ear cleaning, brushing, drying, and professional styling. Using premium products for optimal pet care.',
    '2to3Hours': '2-3 hours',
    'fullBodyWash': 'Full body wash and rinse',
    'brushing': 'Professional brushing and detangling',
    'drying': 'Gentle blow drying',
    'stylingCut': 'Professional styling and cutting',
    'appointmentRequired': 'Appointment scheduling required',
    'petBehaviorAssessment': 'Pet behavior assessment',
    'ownerPresenceMayBeRequired': 'Owner presence may be required',
    'premiumShampooIncluded': 'Premium shampoo and conditioner included',
    'nailPolishOptional': 'Nail polish application (optional)',
    'fragranceOptions': 'Pet-safe fragrance options available',
    'dogTrainingFull': 'Professional dog training sessions focusing on basic obedience, behavior correction, and socialization. Customized training plans with progress tracking and ongoing support.',
    '1HourSession': '1-hour session',
    'basicObedienceTraining': 'Basic obedience training',
    'behaviorCorrection': 'Behavior correction techniques',
    'socializationTraining': 'Socialization training',
    'customTrainingPlan': 'Customized training plan',
    'progressTracking': 'Progress tracking and assessment',
    'homeVisitOptions': 'Home visit training options',
    'ownerParticipationRequired': 'Owner participation required',
    'sessionPackageRecommended': 'Training session packages recommended',
    'consistentPractice': 'Consistent practice required',
    'certifiedTrainers': 'Certified professional trainers',
    'positiveReinforcementMethods': 'Positive reinforcement methods',
    'followUpSupport': 'Follow-up support included',
    'comprehensiveExam': 'Comprehensive health examination',
    'vaccinations': 'Vaccinations and boosters',
    'healthReport': 'Detailed health report',
    'followUpConsultation': 'Follow-up consultation included',
    'medicationIfNeeded': 'Medication if needed',
    'professionalService': 'Professional service guarantee',
    'qualifiedStaff': 'Qualified and experienced staff',
    'safeEnvironment': 'Safe and clean environment',
    'petSpaFull': 'Luxury spa treatment for pets including aromatherapy bath, massage therapy, paw treatment, and relaxing environment with premium products and health check.',
    '3to4Hours': '3-4 hours',
    'aromatherapyBath': 'Aromatherapy bath treatment',
    'massageTherapy': 'Therapeutic massage',
    'pawTreatment': 'Specialized paw treatment',
    'relaxingEnvironment': 'Calm and relaxing environment',
    'healthCheckIncluded': 'Basic health check included',
    'petHealthAssessment': 'Pet health assessment required',
    'noRecentIllness': 'No recent illness required',
    'calmsAnxiousPets': 'Helps calm anxious pets',
    'improvesSkinHealth': 'Improves skin and coat health',
    'bondingExperience': 'Enhances bonding experience',
    'veterinaryCheckupFull': 'Comprehensive veterinary health examination including physical assessment, vaccination updates, dental checkup, weight monitoring, and health record updates by experienced veterinarians.',
    '45MinuteSession': '45-minute session',
    'comprehensiveHealthExam': 'Comprehensive health examination',
    'vaccinationUpdates': 'Vaccination updates and boosters',
    'bloodTestOptional': 'Blood test (optional)',
    'dentalCheckup': 'Dental health checkup',
    'weightMonitoring': 'Weight and growth monitoring',
    'healthRecordUpdate': 'Health record updates',
    'petHealthHistory': 'Pet health history required',
    'fastingIfBloodTest': 'Fasting required if blood test needed',
    'experiencedVeterinarians': 'Experienced veterinary professionals',
    'modernMedicalEquipment': 'Modern medical equipment',
    'followUpCareIncluded': 'Follow-up care and consultation included',
    'contactUs': 'Contact Us',
    'contactUsForBooking': 'Contact us to schedule your booking',
    'call': 'Call',
    'loadingServiceDetails': 'Loading service details...',
    'aboutThisService': 'About This Service',
    'selectServiceAndTime': 'Select service and preferred time',
    'confirmBookingDetails': 'Confirm booking details and payment',
    'receiveConfirmationCall': 'Receive confirmation call',
    'contactForBooking': 'Contact for Booking',
    'bookServiceConfirmation': 'Book {{name}} for ฿{{price}}?',
    'howToBook': 'How to Book',
    'requirements': 'Requirements',

    // Reward Detail - Missing Keys
    'freeBasicGroomingFull': 'Complete basic grooming service including bath, nail trimming, ear cleaning, and basic styling. Perfect for maintaining your pet\'s hygiene and appearance with professional care.',
    'discountPremiumFoodFull': 'Get 20% discount on premium pet food brands. Choose from a wide selection of high-quality nutrition options for your beloved pet.',
    'freeHealthCheckup': 'Free Health Checkup',
    'freeHealthCheckupDesc': 'Comprehensive health examination by professional veterinarian',
    'freeHealthCheckupFull': 'Complete health examination including vital signs check, physical examination, and basic health assessment. Professional consultation with detailed health report.',
    'premiumToyBundleFull': 'Curated collection of 5 premium pet toys including interactive puzzle toys, durable chew toys, and engaging play items to keep your pet entertained and mentally stimulated.',
    'vipSpaPackageFull': 'Luxury 4-hour spa experience including aromatherapy bath, professional massage, nail care, ear cleaning, and premium grooming with relaxation therapy.',
    'validFor90Days': 'Valid for 90 days from redemption',
    'validFor30Days': 'Valid for 30 days from redemption',
    'validFor120Days': 'Valid for 120 days from redemption',
    'validFor60Days': 'Valid for 60 days from redemption',
    'validFor45Days': 'Valid for 45 days from redemption',
    'validFor180Days': 'Valid for 180 days from redemption',
    'advanceBookingRequired': 'Advance booking required',
    'nonTransferable': 'Non-transferable reward',
    'cancellation24Hours': '24-hour cancellation policy applies',
    'cannotCombineOffers': 'Cannot be combined with other offers',
    'inStoreOnly': 'Valid for in-store purchases only',
    'limitOnePerCustomer': 'Limit one per customer',
    'includesBasicExam': 'Includes basic health examination',
    'medicationNotIncluded': 'Medication costs not included',
    'sessionDuration1Hour': 'Session duration: 1 hour',
    'includes5Toys': 'Includes 5 premium toys',
    'inStorePickupOnly': 'In-store pickup only',
    'limitOnePerPet': 'Limit one bundle per pet',
    'includes4HourSession': 'Includes 4-hour spa session',
    'advanceBooking48Hours': '48-hour advance booking required',
    'premiumServicePackage': 'Premium service package included',
    'redeemReward': 'Redeem Reward',
    'redeemError': 'Failed to redeem reward. Please try again.',
    'loadingRewardDetails': 'Loading reward details...',
    'rewardNotFound': 'Reward not found',
    'aboutThisReward': 'About This Reward',
    'validity': 'Validity Period',
    'yourPoints': 'Your Points',
    'howToUse': 'How to Use',
    'redeemWithPoints': 'Redeem with your points',
    'receiveConfirmationEmail': 'Receive confirmation email',
    'bookYourAppointment': 'Book your service appointment',
    'visitStoreToRedeem': 'Visit store to redeem your reward',
    'rewardTemporarilyUnavailable': 'This reward is temporarily unavailable. Please try again later.',
    'earnMorePoints': 'Earn More Points',
    'daysFromRedemption': '{{days}} days from redemption',
    'redeemConfirmation': 'Redeem {{title}} for {{points}} points?',
    'redeemSuccess': '{{title}} has been redeemed successfully!',
    'redeemNow': 'Redeem Now ({{points}} points)',
    'needMorePoints': 'You need {{needed}} more points to redeem this reward',

    // My Coupons Screen - Missing Keys
    'couponUsedSuccessfully': 'Coupon used successfully!',
    'use': 'Use',
    'usableCoupons': 'Available Coupons',
    'usedExpiredCoupons': 'Used & Expired',
    'loadingCoupons': 'Loading coupons...',
    'noUsableCoupons': 'No Available Coupons',
    'noUsedCoupons': 'No Used/Expired Coupons',
    'noUsableCouponsDescription': 'You don\'t have any usable coupons at the moment. Check back later or redeem rewards to get coupons.',
    'noUsedCouponsDescription': 'Your used and expired coupons will appear here.',

  },
  th: {
    // Navigation & Common
    'back': 'กลับ',
    'next': 'ถัดไป',
    'confirm': 'ยืนยัน',
    'cancel': 'ยกเลิก',
    'all': 'ทั้งหมด',
    'save': 'บันทึก',
    'edit': 'แก้ไข',
    'delete': 'ลบ',
    'search': 'ค้นหา',
    'loading': 'กำลังโหลด...',
    'error': 'ข้อผิดพลาด',
    'success': 'สำเร็จ',

    // Tabs
    'home': 'หน้าหลัก',
    'pets': 'สัตว์เลี้ยง',
    'pet': 'สัตว์เลี้ยง',
    'services': 'บริการ',
    'privileges': 'สิทธิพิเศษ',
    'profile': 'โปรไฟล์',

    // Content & Articles
    'articles': 'บทความ',
    'news': 'ข่าวสาร',
    'coupons': 'คูปอง',
    'bookings': 'การจอง',
    'expires': 'หมดอายุ',
    'allArticles': 'บทความทั้งหมด',
    'newsAndAnnouncements': 'ข่าวสารและประกาศ',
    'allCoupons': 'คูปองทั้งหมด',
    'myServices': 'บริการของฉัน',
    'myBookings': 'การจองของฉัน',
    'content': 'เนื้อหา',
    'noArticlesFound': 'ไม่พบบทความในหมวดหมู่นี้',
    'noNewsFound': 'ไม่พบข่าวสารหรือประกาศ',
    'noCouponsFound': 'ไม่พบคูปอง',
    'noServicesFound': 'ไม่พบบริการ',
    'noBookingsFound': 'ไม่พบการจอง',
    'noBookings': 'ไม่มีการจอง',
    'noBookingsDescription': 'คุณยังไม่มีการจองใดๆ จองบริการเพื่อดูการจองที่นี่',
    'noContentFound': 'ไม่พบเนื้อหา',
    'loadingArticles': 'กำลังโหลดบทความ...',
    'announcement': 'ประกาศ',
    'readyToUse': 'พร้อมใช้งาน',
    'unknown': 'ไม่ทราบ',
    'upcoming': 'กำลังจะมาถึง',
    'completed': 'เสร็จสิ้น',

    // Hotel Booking
    'bookRoom': 'จองห้อง',
    'bookingDetails': 'รายละเอียดการจอง',
    'selectDates': 'เลือกวันที่',
    'checkIn': 'เช็คอิน',
    'checkOut': 'เช็คเอาท์',
    'nightsPlural': 'คืน',
    'night': 'คืน',
    'selectPets': 'เลือกสัตว์เลี้ยง',
    'selectPetsDescription': 'เลือกสัตว์เลี้ยงที่ต้องการจอง (สูงสุด {{max}} ตัว)',
    'noPetsAvailable': 'ไม่มีสัตว์เลี้ยงที่เหมาะสมสำหรับโรงแรมประเภทนี้',
    'addPetFirst': 'เพิ่มสัตว์เลี้ยงใหม่ก่อน',
    'bookingSummary': 'สรุปการจอง',
    'totalCost': 'ราคารวม',
    'confirmBooking': 'ยืนยันการจอง',
    'bookingConfirmed': 'จองสำเร็จ!',
    'roomBooked': 'ห้องของคุณได้รับการจองเรียบร้อยแล้ว',
    'roomSize': 'ขนาดห้อง',
    'roomCapacity': 'จำนวนที่รองรับ',
    'bookingId': 'รหัสการจอง',
    'bookingDate': 'วันที่จอง',
    'totalNights': 'รวมคืน',
    'totalAmount': 'ราคารวม',
    'bookingError': 'เกิดข้อผิดพลาดในการจอง กรุณาลองใหม่อีกครั้ง',
    'selectRoom': 'เลือกห้อง',
    'selectRoomDescription': 'เลือกห้องที่ต้องการจองสำหรับสัตว์เลี้ยงของคุณ',
    'noRoomsAvailable': 'ไม่มีห้องว่างสำหรับวันที่เลือก กรุณาเลือกวันอื่นหรือห้องอื่น',
    'petCapacity': 'ความจุสัตว์เลี้ยง',
    'roomType': 'ประเภทห้อง',

    // Pet Details
    'petName': 'ชื่อสัตว์เลี้ยง',
    'breed': 'สายพันธุ์',
    'age': 'อายุ',
    'weight': 'น้ำหนัก',
    'years': 'ปี',
    'kg': 'กิโลกรัม',

    // Services
    'serviceDetail': 'รายละเอียดบริการ',
    'keyFeatures': 'จุดเด่น',
    'whatsIncluded': 'รายการที่รวมอยู่',
    'bookService': 'จอง{{service}}',

    // Rewards
    'rewardDetail': 'รายละเอียดรางวัล',
    'pointsRequired': '{{points}} แต้ม',
    'redeemFor': 'แลกด้วย {{points}} แต้ม',
    'termsConditions': 'เงื่อนไขการใช้งาน',
    'currentlyUnavailable': 'ไม่พร้อมใช้งานในขณะนี้',
    'temporarilyUnavailable': 'รางวัลนี้ไม่พร้อมใช้งานชั่วคราว กรุณาลองใหม่อีกครั้งในภายหลัง',

    // Room Details
    'roomDetails': 'รายละเอียดห้อง',
    'perNight': 'ต่อคืน',
    'size': 'ขนาด',
    'capacity': 'จำนวนที่รองรับ',
    'petSingular': 'ตัว',
    'petPlural': 'ตัว',
    'roomAmenities': 'สิ่งอำนวยความสะดวก',
    'bookingConditions': 'เงื่อนไขการจอง',
    'bookThisRoom': 'จองห้องนี้',
    'roomUnavailable': 'ห้องไม่พร้อมใช้งาน',
    'selectDatesNote': 'คุณสามารถเลือกวันที่และสัตว์เลี้ยงในขั้นตอนถัดไป',

    // Settings/Profile
    'language': 'ภาษา',
    'english': 'English',
    'thai': 'ไทย',
    'changeLanguage': 'เปลี่ยนภาษา',

    // Categories
    'food': 'อาหาร',
    'toys': 'ของเล่น',
    'accessories': 'อุปกรณ์เสริม',
    'medicine': 'ยา',
    'grooming': 'ตัดแต่งขน',
    'training': 'ฝึกสอน',
    'boarding': 'ฝากเลี้ยง',
    'spa': 'สปา',
    'medical': 'การแพทย์',
    'health': 'สุขภาพ',
    'nutrition': 'โภชนาการ',
    'veterinary': 'สัตวแพทย์',
    'emergency': 'ฉุกเฉิน',
    'preventive': 'การป้องกัน',
    'specialist': 'ผู้เชี่ยวชาญ',
    'general': 'การดูแลทั่วไป',

    // Status
    'available': 'พร้อมใช้งาน',
    'unavailable': 'ไม่พร้อมใช้งาน',
    'inStock': 'มีสินค้า',
    'outOfStock': 'สินค้าหมด',
    'add': 'เพิ่ม',

    // Home Screen
    'welcomeToPetShop': 'ยินดีต้อนรับสู่ PetShop',
    'petArticles': 'บทความสัตว์เลี้ยง',
    'myCoupons': 'คูปองของฉัน',
    'currentBookings': 'การจองปัจจุบัน',

    // Pet Card & Form
    'medicalInformation': 'ข้อมูลทางการแพทย์',
    'healthInformation': 'ข้อมูลสุขภาพ',
    'attendingVeterinarian': 'สัตวแพทย์ที่ดูแล',
    'lastSeen': 'พบครั้งสุดท้าย',
    'nextAppointment': 'นัดหมายครั้งต่อไป',
    'congenitalDiseases': 'โรคแต่กำเนิด',
    'allergies': 'อาการแพ้',
    'none': 'ไม่มี',
    'yearsOld': 'ปี',
    'weightKg': '{{weight}} กิโลกรัม',
    'na': 'ไม่มีข้อมูล',
    'at': 'เวลา',

    // Booking Form
    'book': 'จอง',
    'selectPetsLabel': 'เลือกสัตว์เลี้ยง',
    'date': 'วันที่',
    'time': 'เวลา',
    'specialNotes': 'หมายเหตุพิเศษ',
    'anySpecialRequirements': 'ความต้องการพิเศษใดๆ...',
    'bookingAndSummary': 'สรุปการจอง',
    'serviceLabel': 'บริการ: {{service}}',
    'petsSelected': 'สัตว์เลี้ยง: เลือก {{count}} ตัว',
    'total': 'รวม: ฿{{amount}}',
    'bookNow': 'จองเลย',
    'errorSelectPets': 'กรุณาเลือกสัตว์เลี้ยงอย่างน้อย 1 ตัว',
    'errorSelectDateTime': 'กรุณาเลือกวันที่และเวลา',
    'datePlaceholder': 'ปปปป-ดด-วว',
    'timePlaceholder': 'ชช:นน',

    // Alert Messages
    'lazadaAppNotFound': 'ไม่พบแอป Lazada',
    'wouldYouLikeToDownload': 'คุณต้องการดาวน์โหลดแอป Lazada หรือเยียมชมเว็บไซต์?',
    'downloadApp': 'ดาวน์โหลดแอป',
    'openWebsite': 'เปิดเว็บไซต์',
    'unableToOpenLazada': 'ไม่สามารถเปิด Lazada ได้ กรุณาลองใหม่อีกครั้ง',

    // Common UI Elements
    'viewAll': 'ดูทั้งหมด',
    'seeMore': 'ดูเพิ่มเติม',
    'readMore': 'อ่านเพิ่มเติม',

    // Profile Menu
    'menu': 'เมนู',
    'myBookingsSubtitle': 'ดูประวัติบริการของคุณ',
    'myCouponsSubtitle': 'ดูคูปองที่ใช้ได้และใช้แล้ว',
    'notifications': 'การแจ้งเตือน',
    'notificationsSubtitle': 'จัดการการแจ้งเตือนของคุณ',
    'settings': 'การตั้งค่า',
    'settingsSubtitle': 'การตั้งค่าแอป',
    'helpSupport': 'ช่วยเหลือและสนับสนุน',
    'helpSupportSubtitle': 'รับความช่วยเหลือ',
    'aboutPetShop': 'เกี่ยวกับ PetShop',
    'aboutPetShopSubtitle': 'ข้อมูลแอป',
    'signOut': 'ออกจากระบบ',

    // Services Screen
    'petServices': 'บริการสัตว์เลี้ยง',
    'allServices': 'บริการทั้งหมด',
    'petBoarding': 'ฝากเลี้ยงสัตว์',
    'petBoardingDesc': 'บริการฝากเลี้ยงที่ปลอดภัยและสะดวกสบายขณะที่คุณไม่อยู่',
    'professionalGrooming': 'ตัดแต่งขนแบบมืออาชีพ',
    'professionalGroomingDesc': 'บริการตัดแต่งครบวงจร รวมอาบน้ำ ตัดเล็บ และแต่งทรง',
    'dogTraining': 'ฝึกสอนสุนัข',
    'dogTrainingDesc': 'คอร์สฝึกสอนมืออาชีพเพื่อการเชื่อฟังพื้นฐานและพฤติกรรม',
    'petSpa': 'สปาสัตว์เลี้ยง',
    'petSpaDesc': 'บริการสปาผ่อนคลายสำหรับสัตว์เลี้ยงที่คุณรัก',
    'veterinaryCheckup': 'ตรวจสุขภาพสัตวแพทย์',
    'veterinaryCheckupDesc': 'การตรวจสุขภาพครบวงจรโดยสัตวแพทย์ผู้เชี่ยวชาญ',

    // My Pets Screen
    'myPets': 'สัตว์เลี้ยงของฉัน',
    'addNewPet': 'เพิ่มสัตว์เลี้ยงใหม่',
    'noPetsYet': 'ยังไม่มีสัตว์เลี้ยง',
    'addFirstPet': 'เพิ่มสัตว์เลี้ยงตัวแรกของคุณเพื่อเริ่มต้น',
    'removePet': 'ลบสัตว์เลี้ยง',
    'removePetConfirm': 'คุณแน่ใจหรือไม่ที่ต้องการลบ {{name}} ออกจากรายการสัตว์เลี้ยงของคุณ?',
    'remove': 'ลบ',

    // Add Pet Screen
    'addPetTitle': 'เพิ่มสัตว์เลี้ยงใหม่',
    'petPhoto': 'รูปสัตว์เลี้ยง',
    'selectPhoto': 'เลือกรูป',
    'petType': 'ประเภทสัตว์เลี้ยง',
    'dog': 'สุนัข',
    'cat': 'แมว',
    'other': 'อื่นๆ',
    'petDetails': 'รายละเอียดสัตว์เลี้ยง',
    'enterPetName': 'ใส่ชื่อสัตว์เลี้ยง',
    'enterBreed': 'ใส่สายพันธุ์',
    'enterAge': 'ใส่อายุเป็นปี',
    'enterWeight': 'ใส่น้ำหนักเป็นกิโลกรัม',
    'medicalInfo': 'ข้อมูลทางการแพทย์',
    'allergiesOptional': 'อาการแพ้ (ไม่บังคับ)',
    'enterAllergies': 'ใส่อาการแพ้ที่ทราบ',
    'congenitalDiseasesOptional': 'โรคแต่กำเนิด (ไม่บังคับ)',
    'enterDiseases': 'ใส่โรคแต่กำเนิดที่มี',
    'veterinarianInfo': 'ข้อมูลสัตวแพทย์',
    'vetName': 'ชื่อสัตวแพทย์',
    'enterVetName': 'ใส่ชื่อสัตวแพทย์',
    'vetPhone': 'เบอร์โทรศัพท์',
    'enterVetPhone': 'ใส่เบอร์โทรศัพท์',
    'addPet': 'เพิ่มสัตว์เลี้ยง',
    'fillRequiredFields': 'กรุณากรอกข้อมูลที่จำเป็นให้ครบถ้วน',
    'petNameRequired': 'จำเป็นต้องใส่ชื่อสัตว์เลี้ยง',
    'breedRequired': 'จำเป็นต้องใส่สายพันธุ์',
    'ageRequired': 'จำเป็นต้องใส่อายุ',
    'validAge': 'กรุณาใส่อายุที่ถูกต้อง',
    'weightRequired': 'จำเป็นต้องใส่น้ำหนัก',
    'validWeight': 'กรุณาใส่น้ำหนักที่ถูกต้อง',
    'validPhone': 'กรุณาใส่เบอร์โทรที่ถูกต้อง',
    'petAddedSuccess': 'เพิ่ม {{name}} ในรายการสัตว์เลี้ยงเรียบร้อยแล้ว!',
    'basicInformation': 'ข้อมูลพื้นฐาน',
    'healthInformationForm': 'ข้อมูลสุขภาพ',
    'multipleItemsComma': 'ใส่หลายรายการโดยคั่นด้วยเครื่องหมายจุลภาค',
    'veterinaryInformation': 'ข้อมูลสัตวแพทย์',
    'optionalAddLater': 'ไม่บังคับ - สามารถเพิ่มข้อมูลทีหลัง',
    'enterPetNamePlaceholder': 'ใส่ชื่อสัตว์เลี้ยงของคุณ',
    'breedExample': 'เช่น โกลเด้น รีทรีฟเวอร์, เปอร์เซีย',
    'ageYears': 'อายุ (ปี)',
    'weightKgLabel': 'น้ำหนัก (กิโลกรัม)',
    'allergiesExample': 'เช่น ไก่, นม, ถั่ว (ไม่บังคับ)',
    'diseasesExample': 'เช่น โรคกระดูกสะโพก, โรคหัวใจ (ไม่บังคับ)',
    'attendingVet': 'สัตวแพทย์ประจำ',
    'drExample': 'นพ.สมชาย ใจดี (ไม่บังคับ)',
    'veterinarianPhone': 'เบอร์โทรสัตวแพทย์',
    'phoneExample': '066-123-4567 (ไม่บังคับ)',
    'petInformation': 'ข้อมูลสัตว์เลี้ยง',
    'fillAllRequiredFields': 'กรุณากรอกข้อมูลที่จำเป็นทั้งหมด',
    'registerNewFamily': 'ลงทะเบียนสมาชิกครอบครัวใหม่',
    'physicalDetails': 'รายละเอียดทางกายภาพ',
    'separateWithCommas': 'แยกด้วยเครื่องหมายจุลภาค',
    'attendingVeterinarianName': 'ชื่อสัตวแพทย์ประจำ',
    'attendingVeterinarianPhone': 'เบอร์โทรสัตวแพทย์ประจำ',
    'ageInYears': 'อายุเป็นปี',
    'weightInKg': 'น้ำหนักเป็นกิโลกรัม',
    'enterCongenitalDiseases': 'ใส่โรคแต่กำเนิด',
    'petAddedSuccessfully': 'เพิ่มสัตว์เลี้ยงเรียบร้อยแล้ว',
    'failedToAddPet': 'ไม่สามารถเพิ่มสัตว์เลี้ยงได้',
    'pleaseCompleteRequiredFields': 'กรุณากรอกข้อมูลที่จำเป็นให้ครบถ้วน',
    'validationError': 'ข้อผิดพลาดการตรวจสอบ',
    'bathGrooming': 'อาบน้ำและตัดแต่งขน',
    'bookGrooming': 'จองตัดแต่งขน',
    'selectedService': 'บริการที่เลือก',
    'selectDate': 'เลือกวันที่',
    'selectTime': 'เลือกเวลา',
    'selectPetsForGrooming': 'เลือกสัตว์เลี้ยงที่ต้องการตัดแต่งขน',
    'selectedDate': 'วันที่ที่เลือก',
    'totalPrice': 'ราคารวม',
    'booking': 'กำลังจอง...',
    'groomingBookingSuccess': 'การนัดหมาย {{service}} ของคุณถูกจองเรียบร้อยแล้ว!',
    'serviceUnavailable': 'บริการไม่พร้อมให้บริการ',
    'serviceCurrentlyUnavailable': 'บริการนี้ไม่พร้อมให้บริการในขณะนี้ กรุณาลองใหม่อีกครั้ง',
    'noServicesInThisCategory': 'ไม่พบบริการในหมวดหมู่นี้',

    // Privileges Screen
    'privilegesRewards': 'สิทธิพิเศษและรางวัล',
    'pointsBalance': 'ยอดแต้ม',
    'points': 'แต้ม',
    'availableRewards': 'รางวัลที่มี',
    'redeem': 'แลก',
    'redeemPoints': 'แลก {{points}} แต้ม',
    'insufficientPoints': 'แต้มไม่เพียงพอ',

    // Coupons Screen
    'myCouponsTitle': 'คูปองของฉัน',
    'availableCoupons': 'คูปองที่ใช้ได้',
    'usedCoupons': 'คูปองที่ใช้แล้ว',
    'expiredCoupons': 'คูปองที่หมดอายุ',
    'validUntil': 'ใช้ได้ถึง',
    'useCoupon': 'ใช้คูปอง',
    'expired': 'หมดอายุ',
    'used': 'ใช้แล้ว',
    'service': 'บริการ',
    'product': 'สินค้า',
    'special': 'พิเศษ',
    'couponNotFound': 'ไม่พบคูปอง',
    'redeemed': 'ใช้แล้วเมื่อ:',
    'pointsLabel': '{{points}} แต้ม',
    'availableCount': 'ใช้ได้ ({{count}})',
    'usedExpiredCount': 'ใช้แล้วและหมดอายุ ({{count}})',
    'noAvailableCoupons': 'ไม่มีคูปองที่ใช้ได้',
    'noUsedExpiredCoupons': 'ไม่มีคูปองที่ใช้แล้วหรือหมดอายุ',
    'redeemRewardsMessage': 'แลกรางวัลจากส่วนสิทธิพิเศษเพื่อรับคูปองที่ใช้ได้',
    'usedExpiredMessage': 'คูปองที่ใช้แล้วและหมดอายุจะแสดงที่นี่',

    // Coupon Types
    'freeBasicGrooming': 'ตัดแต่งขนฟรี',
    'freeBasicGroomingDesc': 'บริการตัดแต่งครบวงจรสำหรับสัตว์เลี้ยงตัวเล็ก รวมอาบน้ำ ตัดเล็บ และแต่งทรงพื้นฐาน เหมาะสำหรับรักษาความสะอาดและสุขภาพสัตว์เลี้ยง',
    'premiumToyBundle': 'ชุดของเล่นพรีเมียม',
    'premiumToyBundleDesc': 'ชุดรวมของเล่นพรีเมียมสำหรับสัตว์เลี้ยง รวมของเล่นปริศนา ของเล่นเชือก และของเล่นเสียงดัง',
    'discountPremiumFood': 'ส่วนลด 20% อาหารพรีเมียม',
    'discountPremiumFoodDesc': 'ส่วนลดสำหรับอาหารสัตว์เลี้ยงยี่ห้อพรีเมียม',
    'petTrainingSession': 'คอร์สฝึกสอนสัตว์เลี้ยง',
    'petTrainingSessionDesc': 'คอร์สฝึกสอนแบบตัวต่อตัวกับผู้ฝึกมืออาชีพ',
    'vipSpaPackage': 'แพ็กเกจสปา VIP',
    'vipSpaPackageDesc': 'การดูแลสปาระดับหรูพร้อมนวดและอโรมาเธราปี',

    // Booking History
    'bookingHistory': 'ประวัติการจอง',
    'upcomingBookings': 'กำลังจะมาถึง',
    'pastBookings': 'ที่ผ่านมา',
    'cancelledBookings': 'ที่ยกเลิก',
    'bookingOn': 'จองเมื่อ',
    'status': 'สถานะ',
    'confirmed': 'ยืนยันแล้ว',
    'pending': 'รอดำเนินการ',
    'cancelled': 'ยกเลิก',

    // Service Detail
    'bookThisService': 'จองบริการนี้',
    'pricePerSession': '฿{{price}} ต่อครั้ง',
    'serviceIncludes': 'บริการรวม',
    'bookingInformation': 'ข้อมูลการจอง',
    'keyFeaturesService': 'จุดเด่น',
    'whatsIncludedService': 'สิ่งที่รวมอยู่',
    'serviceNotFound': 'ไม่พบบริการ',
    'myServiceDetail': 'รายละเอียดบริการของฉัน',
    'serviceUsed': 'ใช้แล้ว',
    'serviceExpired': 'หมดอายุ',
    'purchased': 'ซื้อเมื่อ',
    'purchasedOn': 'ซื้อเมื่อ',
    'expiresOn': 'หมดอายุ',
    'usedOn': 'ใช้เมื่อ',
    'useService': 'ใช้บริการ',
    'confirmUseService': 'คุณแน่ใจหรือไม่ที่จะใช้บริการนี้?',
    'serviceUsedMessage': 'บริการได้ถูกทำเครื่องหมายว่าใช้แล้วเรียบร้อย',
    'loadingServices': 'กำลังโหลดบริการ...',
    'noServices': 'ไม่พบบริการ',
    'noServicesDescription': 'บริการที่ซื้อของคุณจะปรากฏที่นี่',
    'viewDetails': 'ดูรายละเอียด',
    'premiumService': 'บริการพรีเมียม',
    'bookAgain': 'จองอีกครั้ง',
    'purchaseAgain': 'ซื้ออีกครั้ง',
    'purchaseService': 'ซื้อบริการ',
    'purchaseServiceConfirmation': 'คุณแน่ใจหรือไม่ที่จะซื้อ {{name}} ในราคา {{price}}?',
    'purchase': 'ซื้อ',
    'unknownService': 'บริการที่ไม่ทราบ',
    'purchaseSuccess': 'ซื้อสำเร็จ',
    'viewMyServices': 'ดูบริการของฉัน',
    'servicePurchasedSuccessfully': 'ซื้อ {{name}} สำเร็จแล้ว!',
    'bookingSuccess': 'จองสำเร็จ',
    'serviceBookedSuccessfully': 'จองบริการสำเร็จแล้ว!',

    // Service Types & Descriptions
    'climatControlled': 'ห้องส่วนตัวปรับอากาศ',
    'regularFeeding': 'ตารางการให้อาหารสม่ำเสมอ',
    'dailyExercise': 'การออกกำลังกายและเล่นทุกวัน',
    'petSocialization': 'การเข้าสังคมกับสัตว์เลี้ยงอื่นๆ',
    'staffSupervision': 'การดูแลโดยเจ้าหน้าที่ 24/7',
    'emergencyVetCare': 'การดูแลสัตวแพทย์ฉุกเฉิน',
    'dailyPhotoUpdates': 'การอัปเดตรูปภาพทุกวัน',
    'optionalGrooming': 'บริการตัดแต่งขน (ตัวเลือก)',
    'bathAndDry': 'อาบน้ำและเป่าขนแบบมืออาชีพ',
    'nailTrimming': 'ตัดและตะไบเล็บ',
    'earCleaning': 'ทำความสะอาดและตรวจหู',
    'furStyling': 'แต่งทรงขนแบบมืออาชีพ',
    'premiumProducts': 'แชมพูและครีมนวดคุณภาพพรีเมียม',
    'healthCheckDuring': 'ตรวจสุขภาพพื้นฐานระหว่างการบริการ',

    // Pet Hospital
    'petHospital': 'โรงพยาบาลสัตว์',
    'petHospitalDescription': 'พบสัตวแพทย์ผู้เชี่ยวชาญ ดูแลครบวงจร เพื่อสุขภาพและความสุขของสัตว์เลี้ยงคุณ',
    'chooseHospitalType': 'เลือกประเภทสัตวแพทย์',
    'selectHospitalForPet': 'เลือกประเภทการรักษาที่สัตว์เลี้ยงของคุณต้องการ',
    'specialistHospital': 'สัตวแพทย์เฉพาะทาง',
    'specialistHospitalDesc': 'การดูแลโดยผู้เชี่ยวชาญสำหรับโรคที่ซับซ้อนและการรักษาเฉพาะทาง',
    'generalHospital': 'สัตวแพทย์อายุกรรม',
    'generalHospitalDesc': 'ตรวจสุขภาพทั่วไป ฉีดวัคซีน และการดูแลสุขภาพพื้นฐาน',
    'bookAppointment': 'นัดหมายแพทย์',
    'availableSlots': 'ช่วงเวลาที่ว่าง',
    'fullyBooked': 'เต็มแล้ว',
    'additionalInformation': 'ข้อมูลเพิ่มเติม',
    'describeSymptoms': 'กรุณาอธิบายอาการหรือความกังวลของสัตว์เลี้ยง',
    'confirmAppointment': 'ยืนยันการนัดหมาย',

    // Pet Hotel
    'petHotel': 'โรงแรมสัตว์เลี้ยง',
    'roomTypes': 'ประเภทห้อง',
    'standardRoom': 'ห้องมาตรฐาน',
    'deluxeRoom': 'ห้องดีลักซ์',
    'suiteRoom': 'ห้องสวีท',
    'viewRooms': 'ดูห้องที่ว่าง',
    'bookHotel': 'จองที่พัก',
    'nights': ' คืน',
    'amenities': 'สิ่งอำนวยความสะดวก',
    'specialRequestsPlaceholder': 'เช่น ความต้องการอาหารพิเศษ, ยา, กิจวัตรประจำวัน...',


    // Quick Actions
    'quickBooking': 'จองด่วน',
    'emergencyVet': 'แพทย์ฉุกเฉิน',
    'petGrooming': 'ตัดแต่งขน',
    'petStore': 'ร้านสัตว์เลี้ยง',

    // New Translation Keys
    'groomingService': 'บริการดูแลทำความสะอาด',
    'cannotBeCancelled': 'ไม่สามารถยกเลิกได้',
    'noUpcomingBookings': 'คุณไม่มีการจองที่กำลังจะมาถึง',
    'noCompletedBookings': 'คุณไม่มีการจองที่เสร็จสิ้น',
    'noBookingsYet': 'คุณยังไม่ได้ทำการจองใดๆ',
    'choosePetType': 'เลือกประเภทสัตว์เลี้ยงของคุณ',
    'selectHotelForPet': 'เลือกโรงแรมที่ออกแบบมาโดยเฉพาะสำหรับสัตว์เลี้ยงของคุณ',
    'dogHotel': 'โรงแรมสำหรับสุนัข',
    'catHotel': 'โรงแรมสำหรับแมว',
    'hotelNotFound': 'ไม่พบโรงแรม',
    'hotelRooms': 'ห้องพักของโรงแรม',
    'loadingRooms': 'กำลังโหลดห้องพัก...',
    'availableRooms': 'ห้องพักที่ว่าง',
    'selectDatesNextStep': 'คุณสามารถเลือกวันที่และสัตว์เลี้ยงในขั้นตอนถัดไป',
    'checkInDate': 'วันที่เข้าพัก',
    'checkOutDate': 'วันที่ออก',
    'selectPetsMax': 'เลือกสัตว์เลี้ยง (สูงสุด {{max}} ตัว)',
    'selectedOfMax': 'เลือกแล้ว: {{selected}} จาก {{max}}',
    'selectAtLeastOnePet': 'กรุณาเลือกสัตว์เลี้ยงอย่างน้อย 1 ตัวสำหรับการจองนี้',
    'bookingDetailsConfirm': 'รายละเอียดการจอง:\\n\\n• โรงแรม: {{hotel}}\\n• ห้อง: {{room}}\\n• {{pets}}: {{petNames}}\\n• เข้าพัก: {{checkIn}}\\n• ออก: {{checkOut}}\\n• คืน: {{nights}}\\n• ยอดรวม: ${{total}}\\n\\nยืนยันการจองนี้หรือไม่?',
    'bookingConfirmationMessage': 'การจองโรงแรมของคุณได้รับการยืนยันแล้ว!\\n\\nรหัสการจอง: {{bookingId}}\\n\\nคุณจะได้รับอีเมลยืนยันในไม่ช้า',
    'bookingInfoNotFound': 'ไม่พบข้อมูลการจอง',
    'professionalVeterinaryCare': 'การดูแลสัตวแพทย์มืออาชีพ',
    'chooseSpecialistVeterinarians': 'เลือกจากสัตวแพทย์ผู้เชี่ยวชาญของเราเพื่อให้การดูแลที่ดีที่สุดสำหรับสัตว์เลี้ยงที่คุณรัก',
    'selectSpecialist': 'เลือกผู้เชี่ยวชาญ',
    'selectBookAppointment': 'เลือกและจองนัดหมาย',
    'specialistNotFound': 'ไม่พบผู้เชี่ยวชาญ',
    'booked': 'จองแล้ว',
    'additionalInfoOptional': 'ข้อมูลเพิ่มเติม (ไม่บังคับ)',
    'appointmentReason': 'เหตุผลในการนัดหมาย',
    'appointmentReasonPlaceholder': 'เช่น ตรวจสุขภาพทั่วไป, ฉีดวัคซีน, ตรวจติดตาม...',
    'initialSymptoms': 'อาการเบื้องต้น',
    'symptomsPlaceholder': 'อธิบายอาการที่คุณสังเกตเห็น...',
    'requestSpecificVet': 'ขอสัตวแพทย์คนใดเป็นพิเศษ',
    'vetNamePlaceholder': 'กรอกชื่อสัตวแพทย์หากคุณมีความต้องการเฉพาะ...',
    'additionalNotes': 'หมายเหตุเพิ่มเติม',
    'additionalNotesPlaceholder': 'ข้อมูลเพิ่มเติมใดๆ สำหรับสัตวแพทย์...',
    'bookingsCannotBeCancelled': 'การจองไม่สามารถยกเลิกได้หลังจากยืนยันแล้ว',
    'incompleteInformation': 'ข้อมูลไม่ครบถ้วน',
    'selectTimeAndPet': 'กรุณาเลือกเวลาและสัตว์เลี้ยงสำหรับการนัดหมาย',
    'bookingCannotBeCancelledConfirm': 'สำคัญ: การจองนี้ไม่สามารถยกเลิกได้หลังจากยืนยันแล้ว\nคุณแน่ใจหรือไม่ที่จะดำเนินการต่อ?',
    'appointmentBookedSuccessfully': 'การนัดหมายของคุณได้รับการจองสำเร็จแล้ว\\n\\nรหัสการจอง: {{bookingId}}\\n\\nคุณจะได้รับอีเมลยืนยันในไม่ช้า',
    'bookingInProgress': 'กำลังจอง...',
    'loadingBookings': 'กำลังโหลดการจอง...',
    'loadingBookingData': 'กำลังโหลดข้อมูลการจอง...',
    'failedToCreateBooking': 'จองไม่สำเร็จ',
    'bookingFailed': 'การจองล้มเหลว',

    // Bath & Grooming
    'professionalGroomingServices': 'บริการตัดแต่งขนมืออาชีพ',
    'chooseGroomingService': 'เลือกจากบริการตัดแต่งขนมืออาชีพของเราเพื่อให้สัตว์เลี้ยงของคุณสะอาดและมีสุขภาพดี',
    'selectGroomingService': 'เลือกบริการตัดแต่งขน',
    'included': 'รวมในบริการ',
    'selectService': 'เลือกบริการ',
    'changeService': 'เปลี่ยนบริการ',
    'selectPet': 'เลือกสัตว์เลี้ยง',
    'choosePetForGrooming': 'เลือกสัตว์เลี้ยงที่คุณต้องการจองบริการตัดแต่งขน',
    'yearsOldSimple': 'ปี',
    'bookGroomingService': 'จองบริการตัดแต่งขน',
    'groomingBookingNote': 'การนัดหมายตัดแต่งขนของคุณจะได้รับการยืนยันในไม่ช้า',
    'selectServiceAndPet': 'กรุณาเลือกบริการตัดแต่งขนและสัตว์เลี้ยงสำหรับการจอง',
    'groomingBookingConfirmedTitle': 'การจองสำเร็จ',
    'groomingBookingConfirmedMessage': 'บริการตัดแต่งขนของคุณได้รับการจองสำเร็จแล้ว!\\n\\nบริการ: {{service}}\\nสัตว์เลี้ยง: {{pet}}\\nราคา: ${{price}}\\nระยะเวลา: {{duration}}\\nรหัสการจอง: {{bookingId}}\\n\\nเราจะติดต่อคุณเพื่อนัดหมายเวลา',
    'ok': 'ตกลง',
    'bath': 'อาบน้ำ',
    'combo': 'คอมโบ',
    'comboPackages': 'แพ็กเกจคอมโบ',

    // Loyalty Card
    'PetShopPoints': 'PetShop พอยต์',
    'loyaltyRewards': 'รางวัลสมาชิก',
    'member': 'สมาชิก',
    'availablePoints': 'พอยต์ที่ใช้ได้',
    'earnedTotal': 'รวม {{points}} พอยต์ที่ได้รับ',

    // Services
    'noServicesAvailable': 'ไม่มีบริการในขณะนี้',

    // Coupon Detail
    'couponDetail': 'รายละเอียดคูปอง',
    'loadingCouponDetail': 'กำลังโหลดรายละเอียดคูปอง...',
    'retry': 'ลองใหม่',
    'discount': 'ส่วนลด',
    'percentageDiscount': 'ส่วนลดเป็นเปอร์เซ็นต์',
    'fixedDiscount': 'ส่วนลดจำนวนคงที่',
    'termsAndConditions': 'เงื่อนไขและข้อตกลง',
    'useCouponConfirm': 'คุณแน่ใจหรือไม่ที่จะใช้คูปองนี้?',
    'useCouponSuccess': 'ใช้คูปองสำเร็จแล้ว!',
    'confirmUseCoupon': 'ยืนยันการใช้คูปอง',
    'couponUsed': 'คูปองถูกใช้แล้ว',
    'couponUsedDescription': 'คูปองนี้ถูกใช้ไปแล้วและไม่สามารถใช้อีกครั้งได้',
    'couponExpired': 'คูปองหมดอายุ',
    'couponExpiredDescription': 'คูปองนี้หมดอายุแล้วและไม่สามารถใช้งานได้',
    'noImage': 'ไม่มีรูปภาพ',
    'usingCoupon': 'กำลังใช้คูปอง...',

    // Service Detail - Missing Keys (Thai)
    'petBoardingFull': 'บริการฝากเลี้ยงสัตว์ครบวงจรพร้อมการดูแล 24 ชั่วโมง ที่พักสะดวกสบาย อาหารปกติ และการออกกำลังกายทุกวัน สัตว์เลี้ยงของคุณจะได้รับการดูแลในสภาพแวดล้อมที่ปลอดภัยและสะอาดโดยเจ้าหน้าที่มีประสบการณ์',
    '24hourSupervision': 'การดูแลโดยเจ้าหน้าที่ 24 ชั่วโมง',
    'comfortableAccommodation': 'ที่พักสะดวกสบาย',
    'feedingService': 'บริการให้อาหารปกติ',
    'playTime': 'เวลาเล่นทุกวัน',
    'emergencyVetAccess': 'เข้าถึงสัตวแพทย์ฉุกเฉิน',
    'vaccinationRecord': 'ต้องมีบันทึกการฉีดวัคซีนปัจจุบัน',
    'advanceBooking': 'แนะนำให้จองล่วงหน้า',
    'petHealthCertificate': 'ต้องมีใบรับรองสุขภาพสัตว์เลี้ยง',
    'pickupDropoffAvailable': 'มีบริการรับ-ส่ง',
    'specialDietAccommodated': 'รองรับความต้องการด้านอาหารพิเศษ',
    'medicationAdministered': 'มีบริการให้ยา',
    'professionalGroomingFull': 'บริการตัดแต่งขนมืออาชีพครบวงจร รวมอาบน้ำ ตัดเล็บ ทำความสะอาดหู แปรงขน เป่าแห้ง และแต่งทรงแบบมืออาชีพ ใช้ผลิตภัณฑ์คุณภาพพรีเมียมเพื่อการดูแลสัตว์เลี้ยงอย่างเหมาะสม',
    '2to3Hours': '2-3 ชั่วโมง',
    'fullBodyWash': 'อาบน้ำและล้างทั่วตัว',
    'brushing': 'การแปรงขนแบบมืออาชีพ',
    'drying': 'การเป่าแห้งอย่างอ่อนโยน',
    'stylingCut': 'การแต่งทรงและตัดแบบมืออาชีพ',
    'appointmentRequired': 'ต้องนัดหมายล่วงหน้า',
    'petBehaviorAssessment': 'การประเมินพฤติกรรมสัตว์เลี้ยง',
    'ownerPresenceMayBeRequired': 'อาจต้องให้เจ้าของอยู่ด้วย',
    'premiumShampooIncluded': 'รวมแชมพูและครีมนวดพรีเมียม',
    'nailPolishOptional': 'ทาเล็บ (เพิ่มเติม)',
    'fragranceOptions': 'มีตัวเลือกน้ำหอมที่ปลอดภัยสำหรับสัตว์เลี้ยง',
    'dogTrainingFull': 'คอร์สฝึกสอนสุนัขมืออาชีพที่เน้นการเชื่อฟังพื้นฐาน การแก้ไขพฤติกรรม และการเข้าสังคม แผนการฝึกสอนที่ปรับแต่งได้พร้อมการติดตามความคืบหน้าและการสนับสนุนอย่างต่อเนื่อง',
    '1HourSession': '1 ชั่วโมงต่อครั้ง',
    'basicObedienceTraining': 'การฝึกเชื่อฟังพื้นฐาน',
    'behaviorCorrection': 'เทคนิคการแก้ไขพฤติกรรม',
    'socializationTraining': 'การฝึกเข้าสังคม',
    'customTrainingPlan': 'แผนการฝึกสอนที่ปรับแต่งได้',
    'progressTracking': 'การติดตามและประเมินความคืบหน้า',
    'homeVisitOptions': 'ตัวเลือกการฝึกสอนที่บ้าน',
    'ownerParticipationRequired': 'ต้องมีเจ้าของร่วมด้วย',
    'sessionPackageRecommended': 'แนะนำแพ็กเกจคอร์สฝึกสอน',
    'consistentPractice': 'ต้องฝึกฝนอย่างสม่ำเสมอ',
    'certifiedTrainers': 'ผู้ฝึกมืออาชีพที่ได้รับการรับรอง',
    'positiveReinforcementMethods': 'วิธีการเสริมแรงเชิงบวก',
    'followUpSupport': 'รวมการสนับสนุนติดตาม',
    'comprehensiveExam': 'การตรวจสุขภาพแบบครบถ้วน',
    'vaccinations': 'การฉีดวัคซีนและเสริม',
    'healthReport': 'รายงานสุขภาพโดยละเอียด',
    'followUpConsultation': 'รวมการปรึกษาติดตาม',
    'medicationIfNeeded': 'ยาหากจำเป็น',
    'professionalService': 'รับประกันบริการมืออาชีพ',
    'qualifiedStaff': 'พนักงานที่มีคุณภาพและประสบการณ์',
    'safeEnvironment': 'สภาพแวดล้อมที่ปลอดภัยและสะอาด',
    'petSpaFull': 'การดูแลสปาหรูหราสำหรับสัตว์เลี้ยง รวมอาบน้ำอโรมาเธราปี การนวดบำบัด การดูแลอุ้งเท้า และสภาพแวดล้อมผ่อนคลายพร้อมผลิตภัณฑ์พรีเมียมและการตรวจสุขภาพ',
    '3to4Hours': '3-4 ชั่วโมง',
    'aromatherapyBath': 'การอาบน้ำอโรมาเธราปี',
    'massageTherapy': 'การนวดบำบัด',
    'pawTreatment': 'การดูแลอุ้งเท้าพิเศษ',
    'relaxingEnvironment': 'สภาพแวดล้อมสงบและผ่อนคลาย',
    'healthCheckIncluded': 'รวมการตรวจสุขภาพพื้นฐาน',
    'petHealthAssessment': 'ต้องประเมินสุขภาพสัตว์เลี้ยง',
    'noRecentIllness': 'ต้องไม่เจ็บป่วยเมื่อเร็วๆ นี้',
    'calmsAnxiousPets': 'ช่วยทำให้สัตว์เลี้ยงกังวลสงบลง',
    'improvesSkinHealth': 'ปรับปรุงสุขภาพผิวหนังและขน',
    'bondingExperience': 'เสริมสร้างประสบการณ์ความผูกพัน',
    'veterinaryCheckupFull': 'การตรวจสุขภาพสัตวแพทย์ครบวงจร รวมการประเมินร่างกาย การอัปเดตวัคซีน การตรวจฟัน การตรวจน้ำหนัก และการอัปเดตบันทึกสุขภาพโดยสัตวแพทย์ผู้เชี่ยวชาญ',
    '45MinuteSession': '45 นาที',
    'comprehensiveHealthExam': 'การตรวจสุขภาพครบวงจร',
    'vaccinationUpdates': 'การอัปเดตวัคซีนและบูสเตอร์',
    'bloodTestOptional': 'การตรวจเลือด (เลือกได้)',
    'dentalCheckup': 'การตรวจสุขภาพฟัน',
    'weightMonitoring': 'การตรวจสอบน้ำหนักและการเจริญเติบโต',
    'healthRecordUpdate': 'การอัปเดตบันทึกสุขภาพ',
    'petHealthHistory': 'ต้องมีประวัติสุขภาพสัตว์เลี้ยง',
    'fastingIfBloodTest': 'ต้องอดอาหารหากตรวจเลือด',
    'experiencedVeterinarians': 'สัตวแพทย์ผู้เชี่ยวชาญ',
    'modernMedicalEquipment': 'อุปกรณ์การแพทย์ที่ทันสมัย',
    'followUpCareIncluded': 'รวมการดูแลและปรึกษาติดตาม',
    'contactUs': 'ติดต่อเรา',
    'contactUsForBooking': 'ติดต่อเราเพื่อนัดหมายการจอง',
    'call': 'โทร',
    'loadingServiceDetails': 'กำลังโหลดรายละเอียดบริการ...',
    'aboutThisService': 'เกี่ยวกับบริการนี้',
    'selectServiceAndTime': 'เลือกบริการและเวลาที่ต้องการ',
    'confirmBookingDetails': 'ยืนยันรายละเอียดการจองและการชำระเงิน',
    'receiveConfirmationCall': 'รับสายยืนยันการจอง',
    'contactForBooking': 'ติดต่อเพื่อจอง',
    'bookServiceConfirmation': 'จอง {{name}} ในราคา ฿{{price}}?',
    'howToBook': 'วิธีการจอง',
    'requirements': 'ข้อกำหนด',

    // Reward Detail - Missing Keys (Thai)
    'freeBasicGroomingFull': 'บริการตัดแต่งขนพื้นฐานครบวงจร รวมอาบน้ำ ตัดเล็บ ทำความสะอาดหู และการแต่งทรงพื้นฐาน เหมาะสำหรับรักษาสุขอนามัยและรูปลักษณ์สัตว์เลี้ยงของคุณด้วยการดูแลแบบมืออาชีพ',
    'discountPremiumFoodFull': 'รับส่วนลด 20% สำหรับอาหารสัตว์เลี้ยงยี่ห้อพรีเมียม เลือกจากตัวเลือกโภชนาการคุณภาพสูงหลากหลายสำหรับสัตว์เลี้ยงที่คุณรัก',
    'freeHealthCheckup': 'ตรวจสุขภาพฟรี',
    'freeHealthCheckupDesc': 'การตรวจสุขภาพครบวงจรโดยสัตวแพทย์มืออาชีพ',
    'freeHealthCheckupFull': 'การตรวจสุขภาพครบวงจร รวมการตรวจสัญญาณชีพ การตรวจร่างกาย และการประเมินสุขภาพพื้นฐาน การปรึกษาแพทย์มืออาชีพพร้อมรายงานสุขภาพโดยละเอียด',
    'premiumToyBundleFull': 'ชุดรวมของเล่นพรีเมียม 5 ชิ้นที่คัดสรรมาเป็นพิเศษ รวมของเล่นปริศนาเชิงโต้ตอบ ของเล่นเคี้ยวที่ทนทาน และไอเท็มเล่นที่น่าสนใจเพื่อให้สัตว์เลี้ยงของคุณเพลิดเพลินและกระตุ้นจิตใจ',
    'vipSpaPackageFull': 'ประสบการณ์สปาหรู 4 ชั่วโมง รวมการอาบน้ำอโรมาเธราปี การนวดแบบมืออาชีพ การดูแลเล็บ การทำความสะอาดหู และการตัดแต่งพรีเมียมพร้อมการบำบัดผ่อนคลาย',
    'validFor90Days': 'ใช้ได้ 90 วันนับจากวันแลก',
    'validFor30Days': 'ใช้ได้ 30 วันนับจากวันแลก',
    'validFor120Days': 'ใช้ได้ 120 วันนับจากวันแลก',
    'validFor60Days': 'ใช้ได้ 60 วันนับจากวันแลก',
    'validFor45Days': 'ใช้ได้ 45 วันนับจากวันแลก',
    'validFor180Days': 'ใช้ได้ 180 วันนับจากวันแลก',
    'advanceBookingRequired': 'ต้องจองล่วงหน้า',
    'nonTransferable': 'ไม่สามารถโอนได้',
    'cancellation24Hours': 'มีนโยบายยกเลิก 24 ชั่วโมง',
    'cannotCombineOffers': 'ไม่สามารถใช้ร่วมกับโปรโมชั่นอื่นได้',
    'inStoreOnly': 'ใช้ได้เฉพาะการซื้อในร้านเท่านั้น',
    'limitOnePerCustomer': 'จำกัดหนึ่งชิ้นต่อลูกค้า',
    'includesBasicExam': 'รวมการตรวจสุขภาพพื้นฐาน',
    'medicationNotIncluded': 'ไม่รวมค่ายา',
    'sessionDuration1Hour': 'ระยะเวลาต่อครั้ง: 1 ชั่วโมง',
    'includes5Toys': 'รวมของเล่นพรีเมียม 5 ชิ้น',
    'inStorePickupOnly': 'รับของในร้านเท่านั้น',
    'limitOnePerPet': 'จำกัดหนึ่งชุดต่อสัตว์เลี้ยง',
    'includes4HourSession': 'รวมบริการสปา 4 ชั่วโมง',
    'advanceBooking48Hours': 'ต้องจองล่วงหน้า 48 ชั่วโมง',
    'premiumServicePackage': 'รวมแพ็กเกจบริการพรีเมียม',
    'redeemReward': 'แลกรางวัล',
    'redeemError': 'ไม่สามารถแลกรางวัลได้ กรุณาลองใหม่อีกครั้ง',
    'loadingRewardDetails': 'กำลังโหลดรายละเอียดรางวัล...',
    'rewardNotFound': 'ไม่พบรางวัล',
    'aboutThisReward': 'เกี่ยวกับรางวัลนี้',
    'validity': 'ระยะเวลาการใช้งาน',
    'yourPoints': 'แต้มของคุณ',
    'howToUse': 'วิธีการใช้',
    'redeemWithPoints': 'แลกด้วยแต้มของคุณ',
    'receiveConfirmationEmail': 'รับอีเมลยืนยัน',
    'bookYourAppointment': 'จองนัดหมายบริการของคุณ',
    'visitStoreToRedeem': 'มาที่ร้านเพื่อแลกรางวัลของคุณ',
    'rewardTemporarilyUnavailable': 'รางวัลนี้ไม่พร้อมใช้งานชั่วคราว กรุณาลองใหม่อีกครั้งในภายหลัง',
    'earnMorePoints': 'รับแต้มเพิ่ม',
    'daysFromRedemption': '{{days}} วันนับจากการแลก',
    'redeemConfirmation': 'แลก {{title}} ด้วย {{points}} แต้ม?',
    'redeemSuccess': 'แลก {{title}} สำเร็จแล้ว!',
    'redeemNow': 'แลกเลย ({{points}} แต้ม)',
    'needMorePoints': 'คุณต้องการอีก {{needed}} แต้มเพื่อแลกรางวัลนี้',

    // My Coupons Screen - Missing Keys (Thai)
    'couponUsedSuccessfully': 'ใช้คูปองสำเร็จแล้ว!',
    'use': 'ใช้',
    'usableCoupons': 'คูปองที่ใช้ได้',
    'usedExpiredCoupons': 'ใช้แล้ว & หมดอายุ',
    'loadingCoupons': 'กำลังโหลดคูปอง...',
    'noUsableCoupons': 'ไม่มีคูปองที่ใช้ได้',
    'noUsedCoupons': 'ไม่มีคูปองที่ใช้แล้ว/หมดอายุ',
    'noUsableCouponsDescription': 'คุณไม่มีคูปองที่ใช้ได้ในขณะนี้ กรุณาตรวจสอบอีกครั้งในภายหลังหรือแลกรางวัลเพื่อรับคูปอง',
    'noUsedCouponsDescription': 'คูปองที่ใช้แล้วและหมดอายุจะแสดงที่นี่',

  },
};